### ISSUE TITLE
plugin的loader设置为"require"无法加载js

### ISSUE THREAD

**Issue by vicerwang** [richard-chen-1985/fis-parser-velocity#1]
如果将loader设置为"require"，页面加载js部分的代码为
```javascript
require(["/widget/header/header.js", "widget/footer/footer.js"]);
```
在源码中，可以修改成如下
```javascript
if(loader) {
    arrJs.push(jsFile.substring(1, jsFile.lastIndexOf('.')));
} else {
    arrJs.push('<script src="' + jsFile + '"></script>\n');
}
```
最后页面加载js部分的代码为
```javascript
require(["widget/header/header", "widget/footer/footer"]);
```

另外如果采用前端打包方式，即fis3-postpackager-loader，即使将插件的allInOne属性设置为true，依然无法将组件的js打包成一个文件，还需要在page下的html文件中声明依赖：
```html
<!--
    @require widget/header/header.js
    @require widget/footer/footer.js
 -->
```
所以建议在添加require([])代码时，添加fis的依赖语法，以方便打包。

最后还有一个建议，模版的context或者称之为mock数据，可以使用js文件代替json，好处是可以模拟velocity tool中的一些方法，如$math.floor()，使之更加灵活。
js文件：
```javascript
module.exports = {}
```
加载mock数据
```javascript
require(mockPath);
delete require.cache[mockPath];
```

最近我也在写一个fis的解析Velocity模版的插件，看了您的代码，收获很多，非常感谢。

**Comment by richard-chen-1985** [comment]
@vicerwang 非常感谢你的建议。

对于第一个问题，其实是因为fis3-postpackager-loader没有在页面插入resourcemap，你需要在引入requirejs的script标签上加data-loader，比如`<script data-loader src='/path/to/require.js'></script>`，我在test里面加了样例。

第二个问题，在使用模块化框架的时候我其实不建议用allnOne策略，而使用部分打包方式，我自己在使用allInOne仅限于不使用任何模块化框架的情况，不过使用部分打包，如你设置同第一个问题，也是可以加载的。

第三个问题，好吧，velocity核心其实是用的阿里fool2fish [velocity模块](https://github.com/fool2fish/velocity)的，在我做gulp插件的时候就用的json，所以我压根儿还不知道它支不支持js文件做mock。当然，也因为我厂的[JDF](https://github.com/putaoshu/jdf)也是用的json，后续我会看看。
谢谢你的建议，因为我厂用seajs，所以其实对amd没做过多测试，以后多交流吧。

**Comment by vicerwang** [comment]
@richard-chen-1985 感谢你的回答。
第一个问题，我已经重现不了了... ，即使不修改我所说的那部分代码，也是能够成功异步加载js的。不过与是否在script标签添加data-loader属性无关，因为fis默认会把jquery.js/esl.js/mod.js/sea.js当作loader的。
第二个问题，amd下在页面的script中添加require([somemodule])，那么fis就会认为somemodule是要异步加载的js模块，是不会打进包里的，解决这个问题有下面三种方式
1.在html中对js文件声明依赖，allInOne或者packTo部分打包方式皆可，同步加载
2.采用packTo部分打包的方式，所有js文件打成的包都是异步加载的
3.采用allInOne打包方式，将includeAsyncs设置为true，同步加载
我觉得比较好的解决方案还是第一种
另外fis自己的mod.js加载方案就简单很多，直接require(somemodule)就可以，因为这个被认为是同步加载。
第三个问题，看到了您很快的做出了修改，希望能够添加一个commonMock的参数，用来放置一些公用的velocity tool方法，每次渲染模版时，都会将该common mock数据合并到html文件对应的mock数据中，理想的参数应该可以接受一个标示路径的字符串，或者一个数组，或者一个文件夹路径。

**Comment by richard-chen-1985** [comment]
@vicerwang  针对你的建议，我做了些修改，加了两个参

loadSync：为true会进行同步加载，我看使用`<!-- @require 'xxx' -->`声明依赖最终是直接在HTML中插入script标签，所以我索性直接插入了script标签。

commonMock：跟一个相对路径文件，用于全局mock文件。
