### ISSUE TITLE
您好，请问有没有详细的说明文档呢？

### ISSUE THREAD

**Issue by dear-lizhihua** [richard-chen-1985/fis-parser-velocity#4]
我们团队最近想用FIS3来构建前端的项目，恰好我们的后端也是在用Velocity。
现在用您的demo，做如下操作：

> cd example\pure
> fis3 release -d ../output
> 提示：[ERROR] parser.0: Cannot find module 'velocity' [E:/Software/nginx/html/FIS/fis-parser-velocity/example/pure/page/index.vm]
> 不知道是什么原因呢？

**Comment by dear-lizhihua** [comment]
刚才找着了原因，竟然是没有npm install。
1.但是安装了npm包之后，还是提示如下信息：
[ERROR] unable to load plugin [fis3-parser-sass] or [fis-parser-sass]
2.这里我又使用npm install -g fis3-parser-sass命令，提示：
'fis3-parser-sass' is not in the npm registry.
3.最终使用npm install -g fis-parser-sass命令，才成功安装。

接着执行如下命令，成功构建。
cd example\pure
fis3 release -d ../output

**Comment by richard-chen-1985** [comment]
@dear-lizhihua 是的，首先你得了解fis，然后用起来就比较顺利了，当然我还做了一个集成解决方案[fiskit](http://github.com/richard-chen-1985/fiskit)，你也可以看看

**Comment by dear-lizhihua** [comment]
Nice!

**Comment by dear-lizhihua** [comment]
fis-parser-velocity

**Comment by richard-chen-1985** [comment]
@dear-lizhihua 这个主要作用是在本模块有改动的时候，可以方便的进行测试，所以才这样写的
