### ISSUE TITLE
怎么复用jello模板

### ISSUE THREAD

**Issue by hxlniada** [richard-chen-1985/fis-parser-velocity#5]
https://github.com/fex-team/fis3-jello
如果能跟这个结合就好了

**Comment by richard-chen-1985** [comment]
@hxlniada jello已经算比较完备的，我这个主要针对纯前端依赖，不知道你是想在jello用什么功能呢？我有一个[jfk](https://github.com/richard-chen-1985/jfk)项目，从jello分出来的，如果jello不能满足你的需求，你也可以参考我的去修改，或者共同讨论
