### ISSUE TITLE
extends与block支持？

### ISSUE THREAD

**Issue by xingzhewj** [richard-chen-1985/fis-parser-velocity#6]
1、可以支持下extends与block的语法吗？

**Comment by richard-chen-1985** [comment]
@xingzhewj 目前还没有耶，可以参考jello的实现方案，可能满足您的需求

**Comment by xingzhewj** [comment]
唉！不想用jello，自己启动了一个tomcat，还得依赖java环境，感觉不好。要是能实现extend与block，就可以实现vm结构继承了，那就完美了！

**Comment by richard-chen-1985** [comment]
我们现在也是需要前端自己启JAVA，我最近也发现这个事情比较麻烦，前端不应该太关注后端的东西，甚至都不应该启JAVA环境，因为我们有些前端配置的电脑还是比较烂，同时启那么多东西还是比较麻烦，不过我们还是可以完全不需要extend和block的情况下完成开发的

**Comment by xingzhewj** [comment]
唉 本来我也不想让java来影响前端的设计，但是组内有人坚持要用字模版继承父模板的方式来设计，没办法居然仅仅就因为这个思路要改用jello，说是提高通用性，自己感觉没多少提高反而前端设计和环境的非常不纯粹。唉，我也很无奈。
